VERSION = "0.2dev"

BG_WIDTH = 800
BG_HEIGHT = 600
INFO_WIDTH = 600 # info on the RHS
INFO_HEIGHT = BG_HEIGHT
INFO_X = BG_WIDTH
INFO_Y = 0

CONSOLE_WIDTH = BG_WIDTH
CONSOLE_HEIGHT = 400 # console buffer on the bottom
CONSOLE_X = 0
CONSOLE_Y = BG_HEIGHT

STATE_WIDTH = INFO_WIDTH
STATE_HEIGHT = CONSOLE_HEIGHT
STATE_X = BG_WIDTH
STATE_Y = BG_HEIGHT

HUDDLE_WIDTH = BG_WIDTH
HUDDLE_HEIGHT = BG_HEIGHT
HUDDLE_X = 10
HUDDLE_Y = 10


WIDTH = BG_WIDTH + INFO_WIDTH
HEIGHT = BG_HEIGHT + CONSOLE_HEIGHT
FPS = 30

INPUT_COOLDOWN_WINDOW = 200 # in ticks / milliseconds
