VERSION = "0.2dev"

BG_WIDTH = 800
BG_HEIGHT = 600
INFO_WIDTH = 600 # info on the RHS
INFO_HEIGHT = BG_HEIGHT
CONSOLE_WIDTH = BG_WIDTH
CONSOLE_HEIGHT = 400 # console buffer on the bottom
ACTION_WIDTH = INFO_WIDTH
ACTION_HEIGHT = CONSOLE_HEIGHT
STATE_WIDTH = INFO_WIDTH
STATE_HEIGHT = CONSOLE_HEIGHT
HUDDLE_WIDTH = BG_WIDTH
HUDDLE_HEIGHT = BG_HEIGHT


WIDTH = BG_WIDTH + INFO_WIDTH
HEIGHT = BG_HEIGHT + CONSOLE_HEIGHT
FPS = 30

INPUT_COOLDOWN_WINDOW = 200 # in ticks / milliseconds
